name: instagram_clone
description: instagram clone in flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.1
  image_picker: ^0.8.4+4
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
